import axios from 'axios';
import Head from 'next/head';
import { useContext, useEffect, useState } from 'react';
import Banner from '../components/Banner';
import Main from '../components/Main';
import TopBar from '../components/TopBar';
import { useRouter } from 'next/router';
import { Context } from '../context/Context';
import Login from './login';

export default function Home() {
  const [posts, setPosts] = useState([]);
  const { asPath } = useRouter();
  // console.log(router.asPath);
  const { user } = useContext(Context);

  useEffect(() => {
    const fetchPosts = async () => {
      const res = await axios.get('http://localhost:5001/api/posts' + asPath);
      // console.log(res);
      setPosts(res.data);
    };
    fetchPosts();
  }, [asPath]);

  function pageRedirect() {
    window.location.href = '/login';
  }

  if (typeof window !== 'undefined') {
    if (!user) {
      pageRedirect();
    }
  }
  //user의 정보는 Csr에서 얻어지므로 ssr이 먼저 실행되는 상황에서는 오류로 처리됨. useEffect 등 csr로 진행되도록해야함. 앞에 if typeof window 이 조건을 통해서 csr로 진행하게 하여 hydration 해결.

  return (
    <div>
      <Head>
        <title>Blog with MongoDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Main posts={posts} />
    </div>
  );
}
