import Head from 'next/head';
import TopBar from '../components/TopBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <p className="font-[lora] text-3xl">test</p>
      <p className="font-[lora] text-3xl">test</p>
      <p className="font-[lora] text-3xl">test</p>
      <p className="font-[lora] text-3xl">test</p>
      <p className="font-[lora] text-3xl">test</p>
      <p className="font-[lora] text-3xl">test</p>
      <p className="font-[lora] text-3xl">test</p>
      <p className="font-[lora] text-3xl">test</p>
      <p className="font-[lora] text-3xl">test</p>
      <p className="font-[lora] text-3xl">test</p>

      <p>test</p>
      <p>test</p>
      <p>test</p>
      <p>test</p>
      <p>test</p>
      <p>test</p>
      <p>test</p>
      <p>test</p>
      <p>test</p>
      <p>test</p>
      <p>test</p>
      <p>test</p>
      <p>test</p>
    </div>
  );
}
