import Head from 'next/head';
import Banner from '../components/Banner';
import Main from '../components/Main';
import TopBar from '../components/TopBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blog with MongoDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Main />
    </div>
  );
}
