import Head from 'next/head';
import Banner from '../components/Banner';
import Main from '../components/Main';
import Posts from '../components/Posts';
import Sidebar from '../components/Sidebar';
import TopBar from '../components/TopBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <Banner />
      <Main />
    </div>
  );
}
